### ISSUE TITLE
[FEATURE] geolocation permission

### ISSUE THREAD

**Issue by DmitryEfimenko** [ng-web-apis/geolocation#14]
# 🚀 Feature request

### Is your feature request related to a problem?

Having `GEOLOCATION_SUPPORT` injection token does not quite answer the question of whether the developer can use the geolocation Web API. The `GEOLOCATION_SUPPORT` simply checks if `navigator.geolocation` object is available. However, the user may have received the browser popup during one of the previous visits to the website and automatically clicked "Block" (like many of us do these days whenever any popup shows up). In this case, the `GEOLOCATION_SUPPORT` will resolve to true, but `geolocation$` observable will emit an error.

### Describe the solution you'd like

To answer the question of whether the user has allowed the website access to geolocation, we can run the following code:
```js
navigator.permissions.query({ name: 'geolocation' }).then((x) => console.log(x.state))
// this will print "prompt", "denied", or "granted"
```

I wonder if an injection token `GEOLOCATION_PERMISSION` could be introduced that would run the code above under the hood? Given the fact that this API returns a `Promise`, I'm not sure if it can still be an Injection token or if it'll have to be an observable service similar to the `geolocation$`

**[Important]** Something to keep in mind: the support for the API above is somewhat spotty: https://caniuse.com/permissions-api

### Describe alternatives you've considered

[Here](https://stackoverflow.com/a/6092416/894273) people suggest using the second callback for the `navigator.geolocation.watchPosition` method that's called upon an error. This does not really solve the issue for me because calling this function will trigger the popup and I would like to know whether the geolocation Web API is available *before* the popup shows up.

**Comment by waterplea** [comment]
Hi @DmitryEfimenko 

Thank you for bringing this up with a detailed post. Could you explain why you need to know this before subscribing to geolocation and why catching error in the stream is not an option for you? Is the proper error thrown to the stream if permission is denied? Support token is for technical availability, whether or not user denied, allowed or yet to be asked sounds like a task for Permissions API separate library under @ng-web-apis org. Which seems like a good addition, would you be interested in contributing? We are pretty busy right now bring another project we work on to open source. Probably nobody will have time to create Permissions API library until next year.

**Comment by DmitryEfimenko** [comment]
> Could you explain why you need to know this before subscribing to geolocation and why catching error in the stream is not an option for you? Is the proper error thrown to the stream if permission is denied?

Sure. The error thrown in the stream is correct - that's not the issue. I'd like to display a custom message to the user explaining to them why the permissions to the location will be asked. This will increase the likelihood of the user clicking on "Allow" on the following popup.

Similarly, I can see a use-case when a website would want to display some information to the user who already Blocked the permission. Perhaps instructions on how to unblock it.

> would you be interested in contributing?

Sure. Do you mind creating the skeleton of the project?

For the API, I'm thinking of something like:

```ts
interface IPermissionsService {
  state(descriptor: PermissionDescriptor): Observable<PermissionState>;
  revoke(api: PermissionName): Observable<PermissionState>; // future possible API - not to be implemented as a part of v1
}
```
The interfaces `PermissionDescriptor`, `PermissionState`, and `PermissionName` are a part of lib.dom.d.ts.
With that the usage will be:
```ts
class MyComponent {
  geolocationPermission$ = this.permissions.status({ name: 'geolocation' });
  
  constructor(private permissions: PermissionsService) {}
}
```
Permissions API Docs: https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query

**Comment by waterplea** [comment]
Great. I will create a skeleton project when I have time. Not sure if I'll make it today. `PermissionDescriptor` interface seems rather pointless for most cases. How about we add an overload so just the name could be passed as well? There's quite a lot of interfaces extending `PermissionDescriptor`, we should support them too. Maybe we can just extract them with TS from an argument of `Permissions.query`. 

Also, status returns a Promise with `PermissionState` object. It has actual `state` and an `onchange` handler. I think it would be a good idea to wrap it into Observable that would fire on initial Promise resolution and on subsequent change events. `revoke` is marked as obsolete and is not present in TypeScript's interface `Permissions`. You think we should still include it?

And we need to decide on Angular version. We typically ship our libraries with Angular 7 so they could support older versions too. We were going to wait for Ivy for Libraries and release a new major version for all of them built with Ivy but it looks like it is not going to happen soon, Angular 11 still doesn't have it. And Angular 7 runs on old TypeScript that doesn't have types for Permissions API. Looks like we should probably move up to Angular 9 or something. What do you guys think? @MarsiBarsi, @IKatsuba, @demensky, @vladimirpotekhin, @DmitryEfimenko

**Comment by IKatsuba** [comment]
I think we have to move up to Angular 9. Tomorrow Angular 8 LTS will end https://angular.io/guide/releases#support-policy-and-schedule

**Comment by DmitryEfimenko** [comment]
> PermissionDescriptor interface seems rather pointless for most cases. How about we add an overload so just the name could be passed as well?

I like that a lot. Initially, that's what I was thinking of but switched to the `PermissionDescriptor` signature just to make sure that we support all possible use-cases of the original API. Somehow didn't think of the overload possibility to support both cases. This is a great idea.

> There's quite a lot of interfaces extending PermissionDescriptor, we should support them too. Maybe we can just extract them with TS from an argument of `Permissions.query`.

Great idea. Will do.

> status returns a Promise with PermissionState object. It has actual state and an onchange handler. I think it would be a good idea to wrap it into Observable that would fire on initial Promise resolution and on subsequent change events

That's exactly how I was thinking to implement it. That's why the signature returns `Observable`. Here's an updated version of the signature that includes overloads:

```ts
type ArgsOfPermissionsQuery = Parameters<typeof Permissions.prototype.query>[0];

state(name: PermissionName): Observable<PermissionState>;
state(descriptor: ArgsOfPermissionsQuery): Observable<PermissionState>;
```

> `revoke` is marked as obsolete and is not present in TypeScript's interface Permissions. You think we should still include it?

No. This was just to show that the proposed signature is extensible. It will support any future methods that Permissions API will introduce at a later time.

Having the project as Angular 9 sounds good to me.

**Comment by waterplea** [comment]
Hi @DmitryEfimenko 

Sorry for the delay. I've created a skeleton repository ready for you to fork if you're still up for the task:
https://github.com/ng-web-apis/permissions

Just fork, pull, run npm ci and npm start. It's a workspace with demo app ready for code implementation.

**Comment by DmitryEfimenko** [comment]
No problem at all! We all have busy lives. I'm on it!

**Comment by DmitryEfimenko** [comment]
@waterplea While writing a unit test to make sure that status is returned from the cache when there are multiple subscribers I thought of a scenario, which I think could also be addressed: Make sure that the status value is returned from the cache when there are multiple calls to `.state()` for the same permissionName. For example:
```ts
it('Provides status from cache when there are multiple calls to query for the same permissionName', () => {
  const querySpy = spyOn(permissions, 'query').and.callThrough();
  service.state('geolocation').subscribe();
  expect(querySpy).toHaveBeenCalledTimes(1);
  service.state('geolocation').subscribe();
  expect(querySpy).toHaveBeenCalledTimes(1);
});
```
This test will not pass with the regular use of `shareReplay` operator under the hood because each call to `service.state()` creates its own observable in this example.

A while ago I've created [a small utility](https://github.com/ngspot/rxjs#share) to handle exactly this use-case. Do you have any objections if I add this utility to `peerDependencies` and use it?

**Comment by waterplea** [comment]
You can just have a map inside the service. I don't think you need to clear it. It would be at most like 10 cold observables. Our just have it query every time and not cache anything. I believe it's a rather light operation. What do you think, @MarsiBarsi ? I would not use dependencies for such a small library, that's for sure.

**Comment by MarsiBarsi** [comment]
I think it is not a problem for us as library creators. If a user sees some potential issues here, they can solve them in their particular app

**Comment by DmitryEfimenko** [comment]
yeah, introducing a dependency is probably an overkill.  I'll use a map for caching

**Comment by waterplea** [comment]
Maybe caching itself is an overkill. After all we are just asking browser. At worst it would be resolved at the next frame, it's not like we perform any perceptible async operation.

**Comment by DmitryEfimenko** [comment]
sounds good. I won't bother with this use-case then

**Comment by DmitryEfimenko** [comment]
Created a PR for this: https://github.com/ng-web-apis/permissions/pull/1
I'm closing this issue. Let's move our conversation into the PR.
