### ISSUE TITLE
[BUG] Demo page throws an error

### ISSUE THREAD

**Issue by DmitryEfimenko** [ng-web-apis/geolocation#16]
# 🐞 Bug report

### Description

The demo page does not show the geolocation in use. I see there's an error in the console:

![image](https://user-images.githubusercontent.com/2098175/102705532-4d7b4400-4246-11eb-8562-1a3377a297f8.png)

### Reproduction

Go to the [Demo page](https://ng-web-apis.github.io/geolocation/). Open console.

### Expected behavior

Demo page should work

### Versions

N/A

**Comment by waterplea** [comment]
Looks like dependabot bumped one thing too many. @vladimirpotekhin can you fix it? ngx-highlightjs had a breaking change. You can probably just roll back the version, or see how it is done now in updated starter.
