### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sterichards** [ng-web-apis/geolocation#22]
# 🐞 Bug report

### Description

Intermittently, using Chrome with geolocate enabled, calling `this.geolocation$.pipe(take(1)).subscribe(position => {` doesn't have anything returned from the observer

### Reproduction

```
this.geolocation$.pipe(take(1)).subscribe(position => {
                this.latitude = position.coords.latitude;
                this.longitude = position.coords.longitude;
                console.log('a');
            }, () => {
                console.log('b');
            },
            () => {
                console.log('c');
            });

        if (!this.geolocationSupport) {
                console.log('d');
        }
```

None of the console logs happen

http://www.stackblitz.com/...

### Expected behavior

At least attempt to obtain geoposition

### Versions

-   OS: macOS 11.2.3 Big Sur
-   Browser Chrome 89.0.4389.114
-   Angular 11.2.2

### Additional context

Brave - Works
Safari - Works

I have tried over HTTP and HTTPs

I have tried Incognito Chrome. I have tried clearing browser cache

**Comment by 6matko** [comment]
Same here.

**Comment by waterplea** [comment]
This sounds weird. This library is very basic and mostly just translates native API to RxJS Observables. I wonder if this could be issue with Chrome. There are no clear steps to reproduce, right?

**Comment by 6matko** [comment]
I checked it right now with example code in MDN. All worked in Firefox but this time it worked on Chrome but not in Vivaldi browser (Chromium based). Now I doubt that its fault of library.

**Comment by sterichards** [comment]
> This sounds weird. This library is very basic and mostly just translates native API to RxJS Observables. I wonder if this could be issue with Chrome. There are no clear steps to reproduce, right?

Not really. It was intermittent within Chrome for me. No errors or warnings of any kind in the browser console

**Comment by waterplea** [comment]
Looking at the source code for the library I don't see how this could happen unless native `geolocation.watchPosition` bugs out. If anybody notices a pattern in reproduction, feel free to drop a comment and reopen.
