### ISSUE TITLE
[BUG] start:ssr script is not working

### ISSUE THREAD

**Issue by DmitryEfimenko** [ng-web-apis/geolocation#38]
# 🐞 Bug report

### Description

I'm working on creating a PR to upgrade package to use ng v12.

It appears that the current version of the `start:ssr` script is not working.

I'd like to verify it'd be OK if the PR I submit also won't fix that particular issue.

### Reproduction

```
npm install
npm run start:ssr
```

**Comment by waterplea** [comment]
Sure, go ahead and address only the update.

**Comment by waterplea** [comment]
Closing this as all libs are being moved into monorepo.
